//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B20SPT
    {
        public string STT { get; set; }
        public System.DateTime Ngay_Ct { get; set; }
        public string So_Ct { get; set; }
        public string Ma_Dt { get; set; }
        public string Ten_Dt { get; set; }
        public System.DateTime Ngay_Bat_Dau { get; set; }
        public System.DateTime Ngay_Ket_Thuc { get; set; }
        public string Ma_SP { get; set; }
        public string Ten_SP { get; set; }
        public decimal Tien_TB { get; set; }
    }
}
