//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B20SPT_Detail
    {
        public string STT { get; set; }
        public string RowId { get; set; }
        public string Ma_Vt { get; set; }
        public string Ten_Vt { get; set; }
        public string Dvt { get; set; }
        public decimal So_luong { get; set; }
    }
}
