//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B30CTV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B30CTV()
        {
            this.B30CTVDetail = new HashSet<B30CTVDetail>();
        }
    
        public int Id { get; set; }
        public System.Guid CTVId { get; set; }
        public string Ma_dvcs { get; set; }
        public string Ma_CbNv { get; set; }
        public System.DateTime Ngay_Ct { get; set; }
        public string So_CT { get; set; }
        public string Ma_dt { get; set; }
        public string Ma_DT_SAP { get; set; }
        public string Ma_KHC2 { get; set; }
        public string Loai_TP { get; set; }
        public string Loai_KH { get; set; }
        public System.DateTime Create_At { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<B30CTVDetail> B30CTVDetail { get; set; }
    }
}
