//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B30CTVDetail
    {
        public int Id { get; set; }
        public System.Guid CTVId { get; set; }
        public System.Guid RowId { get; set; }
        public string Ma_vt { get; set; }
        public string Ma_Vt_SAP { get; set; }
        public string Ten_Vt { get; set; }
        public string Dvt { get; set; }
        public int So_Luong { get; set; }
        public float Han_Muc { get; set; }
        public string DocumentDoc { get; set; }
        public string Ma_dvcs { get; set; }
    
        public virtual B30CTV B30CTV { get; set; }
    }
}
