//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B30G
    {
        public System.Guid Stt { get; set; }
        public string NV_GiaoHang { get; set; }
        public string Ten_NVGiaoHang { get; set; }
        public string NV_PhuKho { get; set; }
        public string Ten_NVPhuKho { get; set; }
        public string So_Ct { get; set; }
        public System.DateTime Ngay_Ct { get; set; }
        public string NV_TaiXe { get; set; }
        public string Ten_NVTaiXe { get; set; }
        public string Ly_Do { get; set; }
        public string Ma_dvcs { get; set; }
        public bool Isactive { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
