//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B30GDetail
    {
        public System.Guid Stt { get; set; }
        public System.Guid RowId { get; set; }
        public string Ma_Dt { get; set; }
        public string Ten_Dt { get; set; }
        public string So_Hd { get; set; }
        public string Ngay_HD { get; set; }
        public string NV_GiaoNhan { get; set; }
        public bool Giao_HD { get; set; }
        public decimal Tien_HD { get; set; }
        public decimal Tien_Phai_Thu { get; set; }
        public string So_CT1 { get; set; }
        public string Noi_Dung { get; set; }
        public bool Da_Giao_Hang { get; set; }
        public bool Chua_giao_hang { get; set; }
        public bool Isactive { get; set; }
    }
}
